//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3521
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heatmapgenerator.PostService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceProfile", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DeviceProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClientGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<heatmapgenerator.PostService.DeviceType> DeviceTypeField;
        
        private string ExtendedDeviceInfoField;
        
        private string GpsDeviceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ClientGuid {
            get {
                return this.ClientGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientGuidField, value) != true)) {
                    this.ClientGuidField = value;
                    this.RaisePropertyChanged("ClientGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<heatmapgenerator.PostService.DeviceType> DeviceType {
            get {
                return this.DeviceTypeField;
            }
            set {
                if ((this.DeviceTypeField.Equals(value) != true)) {
                    this.DeviceTypeField = value;
                    this.RaisePropertyChanged("DeviceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExtendedDeviceInfo {
            get {
                return this.ExtendedDeviceInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedDeviceInfoField, value) != true)) {
                    this.ExtendedDeviceInfoField = value;
                    this.RaisePropertyChanged("ExtendedDeviceInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string GpsDevice {
            get {
                return this.GpsDeviceField;
            }
            set {
                if ((object.ReferenceEquals(this.GpsDeviceField, value) != true)) {
                    this.GpsDeviceField = value;
                    this.RaisePropertyChanged("GpsDevice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceType", Namespace="http://tempuri.org/")]
    public enum DeviceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MobilePhone = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pda = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PC = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Server = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationStamp", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LocationStamp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private heatmapgenerator.PostService.CellTowerData[] CellTowersField;
        
        private heatmapgenerator.PostService.LocationData LocationDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RecordTimeField;
        
        private heatmapgenerator.PostService.WifiAccessPointData[] WifiAccessPointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public heatmapgenerator.PostService.CellTowerData[] CellTowers {
            get {
                return this.CellTowersField;
            }
            set {
                if ((object.ReferenceEquals(this.CellTowersField, value) != true)) {
                    this.CellTowersField = value;
                    this.RaisePropertyChanged("CellTowers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public heatmapgenerator.PostService.LocationData LocationData {
            get {
                return this.LocationDataField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationDataField, value) != true)) {
                    this.LocationDataField = value;
                    this.RaisePropertyChanged("LocationData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RecordTime {
            get {
                return this.RecordTimeField;
            }
            set {
                if ((this.RecordTimeField.Equals(value) != true)) {
                    this.RecordTimeField = value;
                    this.RaisePropertyChanged("RecordTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public heatmapgenerator.PostService.WifiAccessPointData[] WifiAccessPoints {
            get {
                return this.WifiAccessPointsField;
            }
            set {
                if ((object.ReferenceEquals(this.WifiAccessPointsField, value) != true)) {
                    this.WifiAccessPointsField = value;
                    this.RaisePropertyChanged("WifiAccessPoints");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LocationData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> AltitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> FixQualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> FixTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> HeadingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> SatellitesInSolutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> SatellitesInViewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SignalToNoiseRatioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private heatmapgenerator.PostService.SourceType SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SpeedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Altitude {
            get {
                return this.AltitudeField;
            }
            set {
                if ((this.AltitudeField.Equals(value) != true)) {
                    this.AltitudeField = value;
                    this.RaisePropertyChanged("Altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> FixQuality {
            get {
                return this.FixQualityField;
            }
            set {
                if ((this.FixQualityField.Equals(value) != true)) {
                    this.FixQualityField = value;
                    this.RaisePropertyChanged("FixQuality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> FixType {
            get {
                return this.FixTypeField;
            }
            set {
                if ((this.FixTypeField.Equals(value) != true)) {
                    this.FixTypeField = value;
                    this.RaisePropertyChanged("FixType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Heading {
            get {
                return this.HeadingField;
            }
            set {
                if ((this.HeadingField.Equals(value) != true)) {
                    this.HeadingField = value;
                    this.RaisePropertyChanged("Heading");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SatellitesInSolution {
            get {
                return this.SatellitesInSolutionField;
            }
            set {
                if ((this.SatellitesInSolutionField.Equals(value) != true)) {
                    this.SatellitesInSolutionField = value;
                    this.RaisePropertyChanged("SatellitesInSolution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SatellitesInView {
            get {
                return this.SatellitesInViewField;
            }
            set {
                if ((this.SatellitesInViewField.Equals(value) != true)) {
                    this.SatellitesInViewField = value;
                    this.RaisePropertyChanged("SatellitesInView");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SignalToNoiseRatio {
            get {
                return this.SignalToNoiseRatioField;
            }
            set {
                if ((this.SignalToNoiseRatioField.Equals(value) != true)) {
                    this.SignalToNoiseRatioField = value;
                    this.RaisePropertyChanged("SignalToNoiseRatio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public heatmapgenerator.PostService.SourceType Source {
            get {
                return this.SourceField;
            }
            set {
                if ((this.SourceField.Equals(value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Speed {
            get {
                return this.SpeedField;
            }
            set {
                if ((this.SpeedField.Equals(value) != true)) {
                    this.SpeedField = value;
                    this.RaisePropertyChanged("Speed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CellTowerData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CellTowerData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CellTowerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LocationAreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> MaxSignalStrengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> MinSignalStrengthField;
        
        private string OperatorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> SignalStrengthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CellTowerId {
            get {
                return this.CellTowerIdField;
            }
            set {
                if ((this.CellTowerIdField.Equals(value) != true)) {
                    this.CellTowerIdField = value;
                    this.RaisePropertyChanged("CellTowerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((this.CountryCodeField.Equals(value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LocationAreaCode {
            get {
                return this.LocationAreaCodeField;
            }
            set {
                if ((this.LocationAreaCodeField.Equals(value) != true)) {
                    this.LocationAreaCodeField = value;
                    this.RaisePropertyChanged("LocationAreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> MaxSignalStrength {
            get {
                return this.MaxSignalStrengthField;
            }
            set {
                if ((this.MaxSignalStrengthField.Equals(value) != true)) {
                    this.MaxSignalStrengthField = value;
                    this.RaisePropertyChanged("MaxSignalStrength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> MinSignalStrength {
            get {
                return this.MinSignalStrengthField;
            }
            set {
                if ((this.MinSignalStrengthField.Equals(value) != true)) {
                    this.MinSignalStrengthField = value;
                    this.RaisePropertyChanged("MinSignalStrength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OperatorId {
            get {
                return this.OperatorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorIdField, value) != true)) {
                    this.OperatorIdField = value;
                    this.RaisePropertyChanged("OperatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> SignalStrength {
            get {
                return this.SignalStrengthField;
            }
            set {
                if ((this.SignalStrengthField.Equals(value) != true)) {
                    this.SignalStrengthField = value;
                    this.RaisePropertyChanged("SignalStrength");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WifiAccessPointData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WifiAccessPointData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BssidField;
        
        private string RouterInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SecureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> SignalStrengthField;
        
        private string SsidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Bssid {
            get {
                return this.BssidField;
            }
            set {
                if ((object.ReferenceEquals(this.BssidField, value) != true)) {
                    this.BssidField = value;
                    this.RaisePropertyChanged("Bssid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RouterInfo {
            get {
                return this.RouterInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.RouterInfoField, value) != true)) {
                    this.RouterInfoField = value;
                    this.RaisePropertyChanged("RouterInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Secure {
            get {
                return this.SecureField;
            }
            set {
                if ((this.SecureField.Equals(value) != true)) {
                    this.SecureField = value;
                    this.RaisePropertyChanged("Secure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> SignalStrength {
            get {
                return this.SignalStrengthField;
            }
            set {
                if ((this.SignalStrengthField.Equals(value) != true)) {
                    this.SignalStrengthField = value;
                    this.RaisePropertyChanged("SignalStrength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Ssid {
            get {
                return this.SsidField;
            }
            set {
                if ((object.ReferenceEquals(this.SsidField, value) != true)) {
                    this.SsidField = value;
                    this.RaisePropertyChanged("Ssid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SourceType", Namespace="http://tempuri.org/")]
    public enum SourceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gps = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Map = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PremiumPartner1 = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationPostResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LocationPostResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime TimeStampField;
        
        private bool isSuccessfulField;
        
        private heatmapgenerator.PostService.resultCode ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BatchLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FrequencyField;
        
        private string TrackingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool isSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                if ((this.isSuccessfulField.Equals(value) != true)) {
                    this.isSuccessfulField = value;
                    this.RaisePropertyChanged("isSuccessful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public heatmapgenerator.PostService.resultCode ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ResultString {
            get {
                return this.ResultStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultStringField, value) != true)) {
                    this.ResultStringField = value;
                    this.RaisePropertyChanged("ResultString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int BatchLimit {
            get {
                return this.BatchLimitField;
            }
            set {
                if ((this.BatchLimitField.Equals(value) != true)) {
                    this.BatchLimitField = value;
                    this.RaisePropertyChanged("BatchLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Frequency {
            get {
                return this.FrequencyField;
            }
            set {
                if ((this.FrequencyField.Equals(value) != true)) {
                    this.FrequencyField = value;
                    this.RaisePropertyChanged("Frequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string TrackingId {
            get {
                return this.TrackingIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingIdField, value) != true)) {
                    this.TrackingIdField = value;
                    this.RaisePropertyChanged("TrackingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="resultCode", Namespace="http://tempuri.org/")]
    public enum resultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidToken = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Successful = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PostService.LocationPostServiceSoap")]
    public interface LocationPostServiceSoap {
        
        // CODEGEN: Generating message contract since element name token from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostLocation", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.DeviceProfile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.DeviceType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.LocationStamp[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.LocationStamp))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.CellTowerData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.CellTowerData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.LocationData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.SourceType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.WifiAccessPointData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.WifiAccessPointData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.LocationPostResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.resultCode))]
        heatmapgenerator.PostService.PostLocationResponse PostLocation(heatmapgenerator.PostService.PostLocationRequest request);
        
        // CODEGEN: Generating message contract since element name token from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostLocationOnlyToPhyo", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.DeviceProfile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.DeviceType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.LocationStamp[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.LocationStamp))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.CellTowerData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.CellTowerData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.LocationData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.SourceType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.WifiAccessPointData[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.WifiAccessPointData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.LocationPostResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(heatmapgenerator.PostService.resultCode))]
        heatmapgenerator.PostService.PostLocationOnlyToPhyoResponse PostLocationOnlyToPhyo(heatmapgenerator.PostService.PostLocationOnlyToPhyoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostLocation", Namespace="http://tempuri.org/", Order=0)]
        public heatmapgenerator.PostService.PostLocationRequestBody Body;
        
        public PostLocationRequest() {
        }
        
        public PostLocationRequest(heatmapgenerator.PostService.PostLocationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostLocationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public heatmapgenerator.PostService.DeviceProfile deviceProfile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public heatmapgenerator.PostService.LocationStamp[] locationStamps;
        
        public PostLocationRequestBody() {
        }
        
        public PostLocationRequestBody(object token, heatmapgenerator.PostService.DeviceProfile deviceProfile, heatmapgenerator.PostService.LocationStamp[] locationStamps) {
            this.token = token;
            this.deviceProfile = deviceProfile;
            this.locationStamps = locationStamps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostLocationResponse", Namespace="http://tempuri.org/", Order=0)]
        public heatmapgenerator.PostService.PostLocationResponseBody Body;
        
        public PostLocationResponse() {
        }
        
        public PostLocationResponse(heatmapgenerator.PostService.PostLocationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostLocationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public heatmapgenerator.PostService.LocationPostResponse PostLocationResult;
        
        public PostLocationResponseBody() {
        }
        
        public PostLocationResponseBody(heatmapgenerator.PostService.LocationPostResponse PostLocationResult) {
            this.PostLocationResult = PostLocationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostLocationOnlyToPhyoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostLocationOnlyToPhyo", Namespace="http://tempuri.org/", Order=0)]
        public heatmapgenerator.PostService.PostLocationOnlyToPhyoRequestBody Body;
        
        public PostLocationOnlyToPhyoRequest() {
        }
        
        public PostLocationOnlyToPhyoRequest(heatmapgenerator.PostService.PostLocationOnlyToPhyoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostLocationOnlyToPhyoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public heatmapgenerator.PostService.DeviceProfile deviceProfile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public heatmapgenerator.PostService.LocationStamp[] locationStamps;
        
        public PostLocationOnlyToPhyoRequestBody() {
        }
        
        public PostLocationOnlyToPhyoRequestBody(object token, heatmapgenerator.PostService.DeviceProfile deviceProfile, heatmapgenerator.PostService.LocationStamp[] locationStamps) {
            this.token = token;
            this.deviceProfile = deviceProfile;
            this.locationStamps = locationStamps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostLocationOnlyToPhyoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostLocationOnlyToPhyoResponse", Namespace="http://tempuri.org/", Order=0)]
        public heatmapgenerator.PostService.PostLocationOnlyToPhyoResponseBody Body;
        
        public PostLocationOnlyToPhyoResponse() {
        }
        
        public PostLocationOnlyToPhyoResponse(heatmapgenerator.PostService.PostLocationOnlyToPhyoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PostLocationOnlyToPhyoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public heatmapgenerator.PostService.LocationPostResponse PostLocationOnlyToPhyoResult;
        
        public PostLocationOnlyToPhyoResponseBody() {
        }
        
        public PostLocationOnlyToPhyoResponseBody(heatmapgenerator.PostService.LocationPostResponse PostLocationOnlyToPhyoResult) {
            this.PostLocationOnlyToPhyoResult = PostLocationOnlyToPhyoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface LocationPostServiceSoapChannel : heatmapgenerator.PostService.LocationPostServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LocationPostServiceSoapClient : System.ServiceModel.ClientBase<heatmapgenerator.PostService.LocationPostServiceSoap>, heatmapgenerator.PostService.LocationPostServiceSoap {
        
        public LocationPostServiceSoapClient() {
        }
        
        public LocationPostServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocationPostServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationPostServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationPostServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        heatmapgenerator.PostService.PostLocationResponse heatmapgenerator.PostService.LocationPostServiceSoap.PostLocation(heatmapgenerator.PostService.PostLocationRequest request) {
            return base.Channel.PostLocation(request);
        }
        
        public heatmapgenerator.PostService.LocationPostResponse PostLocation(object token, heatmapgenerator.PostService.DeviceProfile deviceProfile, heatmapgenerator.PostService.LocationStamp[] locationStamps) {
            heatmapgenerator.PostService.PostLocationRequest inValue = new heatmapgenerator.PostService.PostLocationRequest();
            inValue.Body = new heatmapgenerator.PostService.PostLocationRequestBody();
            inValue.Body.token = token;
            inValue.Body.deviceProfile = deviceProfile;
            inValue.Body.locationStamps = locationStamps;
            heatmapgenerator.PostService.PostLocationResponse retVal = ((heatmapgenerator.PostService.LocationPostServiceSoap)(this)).PostLocation(inValue);
            return retVal.Body.PostLocationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        heatmapgenerator.PostService.PostLocationOnlyToPhyoResponse heatmapgenerator.PostService.LocationPostServiceSoap.PostLocationOnlyToPhyo(heatmapgenerator.PostService.PostLocationOnlyToPhyoRequest request) {
            return base.Channel.PostLocationOnlyToPhyo(request);
        }
        
        public heatmapgenerator.PostService.LocationPostResponse PostLocationOnlyToPhyo(object token, heatmapgenerator.PostService.DeviceProfile deviceProfile, heatmapgenerator.PostService.LocationStamp[] locationStamps) {
            heatmapgenerator.PostService.PostLocationOnlyToPhyoRequest inValue = new heatmapgenerator.PostService.PostLocationOnlyToPhyoRequest();
            inValue.Body = new heatmapgenerator.PostService.PostLocationOnlyToPhyoRequestBody();
            inValue.Body.token = token;
            inValue.Body.deviceProfile = deviceProfile;
            inValue.Body.locationStamps = locationStamps;
            heatmapgenerator.PostService.PostLocationOnlyToPhyoResponse retVal = ((heatmapgenerator.PostService.LocationPostServiceSoap)(this)).PostLocationOnlyToPhyo(inValue);
            return retVal.Body.PostLocationOnlyToPhyoResult;
        }
    }
}
